--insert into students(first_name, last_name, birth_date)
--values ('Marc', 'Benichou' , '1998-11-02'),
--('Yoan', 'Cohen', '2010-12-03'),
--('Lea', 'Benichou', '1987-07-27'),
--('Amelia', 'Dux', '1996-04-07'),
--('David', 'Grez', '2003-06-14'),
--('Omer', 'Simpson', '1980-10-03')

--SELECT * FROM  students;
--select first_name, last_name from students
--select* from students where id = 2
--SELECT first_name, last_name FROM students WHERE first_name = 'Marc'  AND 
--last_name = 'Benichou' ;
--select first_name, last_name from students where first_name = 'Marc' or last_name = 'Benichou'
--SELECT first_name FROM students WHERE first_name LIKE '%a%'
--SELECT first_name FROM students WHERE first_name LIKE 'a%'
--select first_name from students where first_name like '%a'
--select * from students where first_name like '%a_';
--SELECT * FROM students WHERE ID = 1 or ID = 2
--SELECT * FROM students WHERE birth_date >= '2000-01-01'
